config/routes.rb
Rails.application.routes.draw do

  root to: 'landing#index'
  get :about, to: 'static_pages#about'
  resources :topics, except: [:show] do
    resources :posts, except: [:show] do
      resources :comments, except: [:show]
    end
  end
  resources :users, only: [:new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  mount ActionCable.server => '/cable'
  post :upvote, to: 'votes#upvote'
  post :downvote, to: 'votes#downvote'

  # get :resetpassword, to: 'password_resets#new'
  # post :password_resets, to: 'password_resets#edit'
  # patch :password_reset, to: 'password_resets#update'

  get :testindex, to: 'landing#testindex' # terrence's testing
  get :test, to: 'test#testing' # terrence's testing
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates :body, length: { minimum: 20 }, presence: true
  paginates_per 4
  has_many :votes

  def total_votes(comment_id)
    Vote.where(comment_id: comment_id).sum(:value)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :js
  before_action :authenticate!, only: [:create, :edit, :update, :destroy]

  def index
    @post = Post.includes(:comments).find(params[:post_id])
    @topic = @post.topic
    @comments = @post.comments.order("created_at DESC").page params[:page]
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @topic = @post.topic
    # @comment = Comment.new(comment_params.merge(post_id: params[:post_id]))
    @comment = current_user.comments.build(comment_params.merge(post_id: @post.id))
    @new_comment = Comment.new

    if @comment.save
      flash.now[:success] = "You've created a new comment."
      CommentBroadcastJob.set(wait: 0.1.seconds).perform_later("create", @comment)
    else
      flash.now[:danger] = @comment.errors.full_messages
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @topic = @post.topic
    @comment = Comment.find_by(id: params[:id])
    authorize @comment
  end

  def update
    @post = Post.find(params[:post_id])
    @topic = @post.topic
    @comment = Comment.find_by(id: params[:id])
    authorize @comment

    if @comment.update(comment_params)
      flash.now[:success] = "You've updated the comment."
      CommentBroadcastJob.set(wait: 0.1.seconds).perform_later("update", @comment)
    else
      flash.now[:danger] = @comment.errors.full_messages
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @topic = @comment.post.topic
    @post = @comment.post
    authorize @comment

    if @comment.destroy
      flash.now[:success] = "You've deleted the comment."
      CommentBroadcastJob.set(wait: 0.1.seconds).perform_later("destroy", @comment)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:image, :body)
  end
end

app/views/comments/_comment.html.erb
<div class="comment flex-child <%=extra_class%>" data-id="<%=comment.id%>">

  <h4><%= comment.body %></h4>
  <div class="form-group">
    <% if comment.image? %>
    <%= image_tag comment.image, class: "img-settings img-responsive center-block" %>
    <% end %>
  </div>
  <% if current_user %>
    <%= link_to upvote_path(comment_id: comment.id), method: :post, remote: true do %>
    <%= fa_icon 'arrow-up 2x', class: 'btn btn-success btn-lg' %>
    <% end %>
  <% end %>
  <span class="votes btn btn-default btn-lg">
    <%= pluralize(comment.total_votes(comment.id), 'vote') %>
  </span>
  <% if current_user %>
    <%= link_to downvote_path(comment_id: comment.id), method: :post, remote: true do %>
    <%= fa_icon 'arrow-down 2x', class: 'btn btn-success btn-lg' %>
    <% end %>
  <% end %>
  <span class="form-group control-panel">
    <% if comment.user == current_user %>
      <%= link_to edit_topic_post_comment_path(post.topic, post, comment), remote: true do %>
      <%= fa_icon 'edit 2x', class: 'btn btn-success btn-lg' %>
      <% end %>
    <% end %>
    <% if comment.user == current_user || current_user&.admin? || current_user&.moderator? %>
      <%= link_to topic_post_comment_path(post.topic, post, comment), remote: true, method: :delete, data: { confirm: "Delete?" } do %>
      <%= fa_icon 'trash 2x', class: 'btn btn-success btn-lg' %>
      <% end %>
    <% end %>
  </span>
</div>

app/views/comments/_edit.html.erb
<%= form_for(comment, url: topic_post_comment_path(post.topic, post, comment), authenticity_token: true, remote: true, html: { id: "comment-update-form", data: { id: @comment.id }, multipart: true }) do |f| %>
<h1 class="text-center">
    Edit Comment
</h1>

<div class="form-group">
    <h4 class="text-center">
        Comment Image
    </h4>
    <div id="preview-image">
        <% if comment.image? %>
        <%= image_tag comment.image, class: "img-settings img-responsive center-block" %>
        <% end %>
    </div>
    <%= f.file_field :image, id: "comment_image_field", class: 'form-control image-uploader' %>

    <h4>
        <%= f.label :body_field, "Body" %>
    </h4>
    <%= f.text_field :body, required: true, id: "comment_body_field", class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.submit "Update Comment", class: "btn btn-success btn-lg", data: { id: @comment.id } %>
    <div class="cancel-button btn btn-success btn-lg" data-id="<%= @comment.id %>">
      Cancel
    </div>
</div>
<% end %>

app/views/comments/_form.html.erb
<div class="flex-child">
<%= form_for(comment, url: topic_post_comments_path(post.topic, post), method: :post, authenticity_token: true, remote: true, html: { id: "comment-create-form", multipart: true }) do |f| %>
<h1 class="text-center">
Create Comment
</h1>

<div class="form-group">
<h4 class="text-center"> Comment Image </h4>
<%= f.file_field :image, id: "comment_image_field", class: 'form-control image-uploader' %>
</div>

<div class="form-group">
<h4> <%= f.label :body_field, "Body" %> </h4>
<%= f.text_field :body, required: true, id: "comment_body_field", class: 'form-control' %>
</div>

<div class="form-group text-center">
<%= f.submit "Create Comment", class: "btn btn-success btn-lg" %>
</div>

<% end %>
</div>

app/views/comments/_remove_edit.html.erb
<div class="comments">
  <div class="flex-parent text-center">
      <div class="flex-child">

<%= form_for(@comment, url: topic_post_comment_path(@topic, @post, @comment), html: { id: "comment-update-form" }) do |f| %>
  <h1 class="text-center">
    Edit Comment
  </h1>

  <div class="form-group">
    <h4 class="text-center"> Comment Image </h4>
    <div id="preview-image">
      <% if @comment.image? %>
        <%= image_tag @comment.image, class: "img-settings img-responsive center-block" %>
      <% end %>
    </div>
    <%= f.file_field :image, id: "comment_image_field", class: 'form-control image-uploader' %>
  </div>


  <div class="form-group">
    <h4> <%= f.label :body_field, "Body" %> </h4>
    <%= f.text_field :body, required: true, id: "comment_body_field", class: 'form-control' %>
  </div>


  <div class="form-group text-center">
    <%= f.submit "Update Comment", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

    </div>
  </div>
</div>

app/views/comments/_remove_new.html.erb
<div class="comments">
  <div class="flex-parent text-center">
      <div class="flex-child">
<%= form_for(@comment, url: topic_post_comments_path(@topic, @post, @comment), html: { id: "comment-create-form" }) do |f| %>
  <h1 class="text-center">
    Create Comment
  </h1>

  <div class="form-group">
    <h4 class="text-center"> Comment Image </h4>
    <%= f.file_field :image, id: "comment_image_field", class: 'form-control image-uploader' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :body_field, "Body" %> </h4>
    <%= f.text_field :body, required: true, id: "comment_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Comment", class: "btn btn-success btn-lg" %>
  </div>

<% end %>
    </div>
  </div>
</div>

app/views/comments/create.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

// have to remove the ajax below otherwise the flash message above and newly created comment wont show when action cable is on, problematic during feature test
  // <% if @comment.persisted? %>
  //   $('#comments-form-container').html("<%=j render partial: 'comments/form', locals: { comment: @new_comment, post: @post } %>")
  // <% end %>

app/views/comments/destroy.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

$('.comment[data-id=<%=@comment.id%>]').remove()

app/views/comments/edit.html.erb
<div class="comments">
  <div class="flex-parent text-center">
      <div class="flex-child">

<%= form_for(@comment, url: topic_post_comment_path(@topic, @post, @comment), html: { id: "comment-update-form" }) do |f| %>
  <h1 class="text-center">
    Edit Comment
  </h1>

  <div class="form-group">
    <h4 class="text-center"> Comment Image </h4>
    <div id="preview-image">
      <% if @comment.image? %>
        <%= image_tag @comment.image, class: "img-settings img-responsive center-block" %>
      <% end %>
    </div>
    <%= f.file_field :image, id: "comment_image_field", class: 'form-control image-uploader' %>
  </div>


  <div class="form-group">
    <h4> <%= f.label :body_field, "Body" %> </h4>
    <%= f.text_field :body, required: true, id: "comment_body_field", class: 'form-control' %>
  </div>


  <div class="form-group text-center">
    <%= f.submit "Update Comment", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

    </div>
  </div>
</div>

app/views/comments/edit.js.erb
$('.comment[data-id=<%=@comment.id%>]').html("<%=j render partial: 'comments/edit', locals: { comment: @comment, post: @comment.post } %>")

$('.cancel-button').on('click', function() {
  $('.comment[data-id=<%=@comment.id%>]').after("<%=j render partial: 'comments/comment', locals: { comment: @comment, post: @comment.post, extra_class: '' } %>").remove()
})

app/views/comments/index.html.erb
<div class="comments index" data-id="<%=@post.id%>">
  <!-- comments page html in here -->
  <div class="flex-child text-center">
    <h1><%="#{@post.title}"%></h1>
    <!-- <%= link_to 'Back to Posts', topic_posts_path(@topic), :class => 'btn btn-success btn-lg' %> -->
    <%= paginate @comments %>
  </div>

  <div id="comments" class="flex-parent text-center">
    <% @comments.each do |comment| %>
      <%= render partial: "comment", locals: {comment: comment, post: @post, extra_class: ''} %>
    <% end %>
  </div>

  <div id="comments-form-container" class="flex-parent text-center">
    <%= render partial: "form", locals: { comment: @comment, post: @post } %>
  </div>

</div>

app/views/comments/new.html.erb
<div class="comments">
  <div class="flex-parent text-center">
      <div class="flex-child">
<%= form_for(@comment, url: topic_post_comments_path(@topic, @post, @comment), html: { id: "comment-create-form" }) do |f| %>
  <h1 class="text-center">
    Create Comment
  </h1>

  <div class="form-group">
    <h4 class="text-center"> Comment Image </h4>
    <%= f.file_field :image, id: "comment_image_field", class: 'form-control image-uploader' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :body_field, "Body" %> </h4>
    <%= f.text_field :body, required: true, id: "comment_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Comment", class: "btn btn-success btn-lg" %>
  </div>

<% end %>
    </div>
  </div>
</div>

app/views/comments/update.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

<% if @comment.persisted? %>
  $('.comment[data-id=<%=@comment.id%>]').replaceWith("<%=j render partial: 'comments/comment', locals: { comment: @comment, post: @post, topic: @topic, extra_class: '' } %>")
<% end %>