config/routes.rb
Rails.application.routes.draw do

  root to: 'landing#index'
  get :about, to: 'static_pages#about'
  resources :topics, except: [:show] do
    resources :posts, except: [:show] do
      resources :comments, except: [:show]
    end
  end
  resources :users, only: [:new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  mount ActionCable.server => '/cable'
  post :upvote, to: 'votes#upvote'
  post :downvote, to: 'votes#downvote'

  # get :resetpassword, to: 'password_resets#new'
  # post :password_resets, to: 'password_resets#edit'
  # patch :password_reset, to: 'password_resets#update'

  get :testindex, to: 'landing#testindex' # terrence's testing
  get :test, to: 'test#testing' # terrence's testing
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts
  belongs_to :user
  validates :title, length: { minimum: 5 }, presence: true
  validates :description, length: { minimum: 20 }, presence: true
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  before_save :check_slug

  def check_slug
    self.slug = title if self.slug != title
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  respond_to :js
  before_action :authenticate!, only: [:create, :edit, :update, :destroy]

  def index
    @topics = Topic.all
    @topic = Topic.new
  end

  # def show
  #   @topic = Topic.find_by(id: params[:id])
  # end

  def create
    @topic = current_user.topics.build(topic_params)
    authorize @topic
    @new_topic = Topic.new

    if @topic.save
      flash.now[:success] = "You've created a new topic."
    else
      flash.now[:danger] = @topic.errors.full_messages
    end
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic
  end

  def update
    @topic = Topic.find(params[:id])
    authorize @topic

    if @topic.update(topic_params)
      flash[:success] = "You've updated the topic."
      redirect_to topics_path
    else
      flash[:danger] = @topic.errors.full_messages
      redirect_to edit_topic_path(@topic)
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    authorize @topic

    if @topic.destroy
      flash[:success] = "You've deleted the topic."
      redirect_to topics_path
    else
      flash[:danger] = @topic.errors.full_messages
      redirect_to topic_path(@topic)
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :description)
  end
end

app/views/topics/_form.html.erb
<div class="flex-child">
  <%= form_for(topic, url: topics_path, method: :post, authenticity_token: true, remote: true, html: { id: "topic-create-form" }) do |f| %>
  <h1 class="text-center">
  Create Topic
  </h1>

  <div class="form-group">
  <h4> <%= f.label :title_field, "Title" %> </h4>
  <%= f.text_field :title, required: true, id: "topic_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
  <h4> <%= f.label :text_field, "Description" %> </h4>
  <%= f.text_field :description, id: "topic_description_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
  <%= f.submit "Create Topic", class: "btn btn-success btn-lg" %>
  </div>

  <% end %>
</div>

app/views/topics/_remove_new.html.erb
<div class="topics">
  <div class="flex-parent text-center">
      <div class="flex-child">  
<%= form_for(@topic, url: topics_path, html: { id: "topic-create-form" }) do |f| %>
  <h1 class="text-center">
    Create Topic
  </h1>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "topic_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Description" %> </h4>
    <%= f.text_field :description, id: "topic_description_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Topic", class: "btn btn-success btn-lg" %>
  </div>

<% end %>
    </div>
  </div>
</div>

app/views/topics/_topic.html.erb
<div class="flex-child">
    <h3><%= link_to topic.title, topic_posts_path(topic) %></h3>
    <h4><%= topic.description %></h4>
    <%= link_to edit_topic_path(topic) do %>
    <%= fa_icon 'edit 2x', class: 'btn btn-success btn-lg' %>
    <% end %>
    <%= link_to topic_path(topic), method: :delete, data: { confirm: "Delete?" } do %>
    <%= fa_icon 'trash 2x', class: 'btn btn-success btn-lg' %>
    <% end %>
</div>

app/views/topics/create.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

  <% if @topic.persisted? %>
    $('#topics').prepend("<%=j render partial: 'topics/topic', locals: { topic: @topic } %>")
    $('#topics-form-container').html("<%=j render partial: 'topics/form', locals: { topic: @new_topic } %>")
  <% end %>

app/views/topics/edit.html.erb
<div class="topics">
  <div class="flex-parent text-center">
      <div class="flex-child">

<%= form_for(@topic, url: topic_path(@topic), html: { id: "topic-update-form" }) do |f| %>
  <h1 class="text-center">
    Edit Topic
  </h1>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "topic_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Description" %> </h4>
    <%= f.text_field :description, id: "topic_description_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Update Topic", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topics">
  <!-- topics page html in here -->
  <div class="flex-child text-center">
    <h1>Topics</h1>
    <!-- <%= link_to 'Add New Topic', new_topic_path, :class => 'btn btn-success btn-lg' %> -->
  </div>

  <div id="topics" class="flex-parent text-center">
      <% @topics.each do |topic| %>
        <%= render partial: "topic", locals: { topic: topic } %>
      <% end %>
  </div>

  <% if current_user&.admin? || current_user&.moderator? %>
    <div id="topics-form-container" class="flex-parent text-center">
      <%= render partial: "form", locals: { topic: @topic } %>
    </div>
  <% end %>

</div>

app/views/topics/new.html.erb
<div class="topics">
  <div class="flex-parent text-center">
      <div class="flex-child">  
<%= form_for(@topic, url: topics_path, html: { id: "topic-create-form" }) do |f| %>
  <h1 class="text-center">
    Create Topic
  </h1>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "topic_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Description" %> </h4>
    <%= f.text_field :description, id: "topic_description_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Topic", class: "btn btn-success btn-lg" %>
  </div>

<% end %>
    </div>
  </div>
</div>