config/routes.rb
Rails.application.routes.draw do

  root to: 'landing#index'
  get :about, to: 'static_pages#about'
  resources :topics, except: [:show] do
    resources :posts, except: [:show] do
      resources :comments, except: [:show]
    end
  end
  resources :users, only: [:new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  mount ActionCable.server => '/cable'
  post :upvote, to: 'votes#upvote'
  post :downvote, to: 'votes#downvote'

  # get :resetpassword, to: 'password_resets#new'
  # post :password_resets, to: 'password_resets#edit'
  # patch :password_reset, to: 'password_resets#update'

  get :testindex, to: 'landing#testindex' # terrence's testing
  get :test, to: 'test#testing' # terrence's testing
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :topic
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  paginates_per 3
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  before_save :check_slug

  def check_slug
    self.slug = title if self.slug != title
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :js
  before_action :authenticate!, only: [:create, :edit, :update, :destroy]

  def index
    @topic = Topic.includes(:posts).find(params[:topic_id])
    @posts = @topic.posts.order("created_at DESC").page params[:page]
    @post = Post.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    # @post = Post.new(post_params.merge(topic_id: params[:topic_id]))
    @post = current_user.posts.build(post_params.merge(topic_id: @topic.id))
    @new_post = Post.new

    if @post.save
      flash.now[:success] = "You've created a new post."
    else
      flash.now[:danger] = @post.errors.full_messages
    end
  end

  def edit
    @post = Post.find(params[:id])
    @topic = @post.topic
    authorize @post
  end

  def update
  #  @topic = Topic.find_by(id: params[:topic_id])
    @post = Post.find(params[:id])
  #  @post = Post.find(params[:id])
    @topic = @post.topic
    authorize @post

    if @post.update(post_params)
      flash[:success] = "You've updated the post."
      redirect_to topic_posts_path(@topic)
    else
      flash[:danger] = @post.errors.full_messages
      redirect_to edit_topic_post_path(@topic, @post)
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @topic = @post.topic
    authorize @post

    if @post.destroy
      flash[:success] = "You've deleted the post."
      redirect_to topic_posts_path(@topic)
    end
  end

  private

  def post_params
    params.require(:post).permit(:image, :title, :body)
  end
end

app/views/posts/_form.html.erb
<div class="flex-child">
<%= form_for(post, url: topic_posts_path(topic), method: :post, authenticity_token: true, remote: true, html: { id: "post-create-form", multipart: true }) do |f| %>
  <h1 class="text-center">
    Create Post
  </h1>

  <div class="form-group">
    <h4 class="text-center"> Post Image </h4>
    <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "post_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Description" %> </h4>
    <%= f.text_field :body, id: "post_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Post", class: "btn btn-success btn-lg" %>
  </div>
<% end %>
</div>

app/views/posts/_post.html.erb
<div class="flex-child">
  <h3><%= link_to post.title, topic_post_comments_path(@topic, post) %></h3>
  <h4><%= post.body %></h4>
  <% if post.image? %>
    <%= image_tag post.image, class: "img-settings img-responsive center-block" %>
  <% end %>
  <%= link_to edit_topic_post_path(@topic, post) do %>
  <%= fa_icon 'edit 2x', class: 'btn btn-success btn-lg' %>
  <% end %>
  <%= link_to topic_post_path(@topic, post), method: :delete, data: { confirm: "Delete?" } do %>
  <%= fa_icon 'trash 2x', class: 'btn btn-success btn-lg' %>
  <% end %>
</div>

app/views/posts/_remove_new.html.erb
<div class="posts">
  <div class="flex-parent text-center">
      <div class="flex-child">
<%= form_for(@post, url: topic_posts_path(@topic, @post), html: { id: "post-create-form" }) do |f| %>
  <h1 class="text-center">
    Create Post
  </h1>

  <div class="form-group">
    <h4 class="text-center"> Post Image </h4>
    <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "post_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Description" %> </h4>
    <%= f.text_field :body, id: "post_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Post", class: "btn btn-success btn-lg" %>
  </div>

<% end %>
    </div>
  </div>
</div>

app/views/posts/create.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

  <% if @post.persisted? %>
    $('#posts').prepend("<%=j render partial: 'posts/post', locals: { post: @post, topic: @post.topic } %>")
    $('#posts-form-container').html("<%=j render partial: 'posts/form', locals: { post: @new_post, topic: @topic } %>")
  <% end %>

app/views/posts/edit.html.erb
<div class="posts">
  <div class="flex-parent text-center">
      <div class="flex-child">

<%= form_for(@post, url: topic_post_path(@topic, @post), html: { id: "post-update-form" }) do |f| %>
  <h1 class="text-center">
    Edit Post
  </h1>

  <div class="form-group">
      <h4 class="text-center"> Post Image </h4>
      <div id="preview-image">
        <% if @post.image? %>
          <%= image_tag @post.image, class: "img-settings img-responsive center-block" %>
        <% end %>
      </div>
      <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "post_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "post_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Update Post", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="posts">
  <!-- posts page html in here -->

  <div class="flex-child text-center">
    <h1><%="#{@topic.title}"%></h1>
    <!-- <%= link_to 'Back to Topics', topics_path, :class => 'btn btn-success btn-lg' %> -->
    <%= paginate @posts %>
  </div>

  <div id="posts" class="flex-parent text-center">
      <% @posts.each do |post| %>
        <%= render partial: "post", locals: { post: post, topic: @topic } %>
      <% end %>
  </div>

  <div id="posts-form-container" class="flex-parent text-center">
      <%= render partial: "form", locals: { post: @post, topic: @topic } %>
  </div>

  </div>

</div>

app/views/posts/new.html.erb
<div class="posts">
  <div class="flex-parent text-center">
      <div class="flex-child">
<%= form_for(@post, url: topic_posts_path(@topic, @post), html: { id: "post-create-form" }) do |f| %>
  <h1 class="text-center">
    Create Post
  </h1>

  <div class="form-group">
    <h4 class="text-center"> Post Image </h4>
    <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "post_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Description" %> </h4>
    <%= f.text_field :body, id: "post_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Post", class: "btn btn-success btn-lg" %>
  </div>

<% end %>
    </div>
  </div>
</div>